//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/ComtroleJogador.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ComtroleJogador : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ComtroleJogador()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ComtroleJogador"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""b4955ea4-fd70-4740-ad5d-176ca60dcfda"",
            ""actions"": [
                {
                    ""name"": ""AcionaArma"",
                    ""type"": ""Button"",
                    ""id"": ""e7b1bd5d-d02c-4d9a-b736-e35a0e0bdf59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Testar"",
                    ""type"": ""Button"",
                    ""id"": ""a91ae9d5-d33a-4264-8ad1-896dc6f60798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4710f572-9abe-4e73-815c-76a17d89f0c8"",
                    ""path"": ""<HID::YiChip BT KB>/button5"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AcionaArma"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58400970-4a2a-4db9-a337-1d3dd5b23904"",
                    ""path"": ""<HID::YiChip BT KB>/button2"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Testar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_AcionaArma = m_Gameplay.FindAction("AcionaArma", throwIfNotFound: true);
        m_Gameplay_Testar = m_Gameplay.FindAction("Testar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_AcionaArma;
    private readonly InputAction m_Gameplay_Testar;
    public struct GameplayActions
    {
        private @ComtroleJogador m_Wrapper;
        public GameplayActions(@ComtroleJogador wrapper) { m_Wrapper = wrapper; }
        public InputAction @AcionaArma => m_Wrapper.m_Gameplay_AcionaArma;
        public InputAction @Testar => m_Wrapper.m_Gameplay_Testar;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @AcionaArma.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAcionaArma;
                @AcionaArma.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAcionaArma;
                @AcionaArma.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAcionaArma;
                @Testar.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTestar;
                @Testar.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTestar;
                @Testar.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTestar;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @AcionaArma.started += instance.OnAcionaArma;
                @AcionaArma.performed += instance.OnAcionaArma;
                @AcionaArma.canceled += instance.OnAcionaArma;
                @Testar.started += instance.OnTestar;
                @Testar.performed += instance.OnTestar;
                @Testar.canceled += instance.OnTestar;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnAcionaArma(InputAction.CallbackContext context);
        void OnTestar(InputAction.CallbackContext context);
    }
}
